# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

# 更新3 Layers 所需參數定義

X 輸入資料集，形式為矩陣，每 1 行代表 1 個訓練樣本。

y 輸出資料集，形式為矩陣，每 1 行代表 1 個訓練樣本。

l0 網路第 1 層，即網路輸入層。

l1 網路第 2 層，常稱作隱藏層。

l2 假定為網路最後一層，隨著訓練進行，其輸出應該逐漸接近正確結果

syn0 第一層權值

syn1 第二層權值

l2_error 該值說明了神經網路預測時“丟失”的數目。

l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。

l1_error 該值為 l2_delta 經 syn1 加權後的結果，從而能夠計算得到中間層/隱層的誤差。

l1_delta 該值為經確信度加權後的神經網路 l1 層的誤差，除了確信誤差很小時，它近似等於 l1_error 。

In [9]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0,0,1,1]]).T

In [16]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
print(syn0)
# define syn1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
syn1 = 2*np.random.random((1,4)) - 1
print(syn1)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[-0.39533485 -0.70648822 -0.81532281 -0.62747958]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [17]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
    l2_error = y - l2
    l2_delta = l2_error * nonlin(l2, True)
    syn1 += np.dot(l1.T, l2_delta)

    # how much did we miss?
    l1_error = np.dot(l2_error, syn1.T) #矩陣相乘
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
     # syn1 update weights
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l2)

Output After Training:
[[9.98765485e-01]
 [9.99089018e-01]
 [6.91718704e-06]
 [9.37681880e-06]]



[[0.00515091 0.00515046 0.00515028 0.00515059]
 [0.00514218 0.00514174 0.00514155 0.00514186]
 [0.49999089 0.49999089 0.49999089 0.49999089]
 [0.49998765 0.49998765 0.49998765 0.49998765]]
